package igoroffline.practice.hamsterchessv2.main.piece.movement;

public enum PieceMovement {
    NEXT_NUMBER, PREVIOUS_NUMBER, NEXT_LETTER, PREVIOUS_LETTER,
    PREVIOUS_LETTER_NEXT_NUMBER, NEXT_LETTER_NEXT_NUMBER, PREVIOUS_LETTER_PREVIOUS_NUMBER, NEXT_LETTER_PREVIOUS_NUMBER,
    PP_LETTER_NEXT_NUMBER, NN_NUMBER_PREVIOUS_LETTER, NN_NUMBER_NEXT_LETTER, NN_LETTER_NEXT_NUMBER,
    PP_LETTER_PREVIOUS_NUMBER, PP_NUMBER_PREVIOUS_LETTER, PP_NUMBER_NEXT_LETTER, NN_LETTER_PREVIOUS_NUMBER,
    PAWN_MOVE_ONE_SQUARE, PAWN_MOVE_TWO_SQUARES, PAWN_ATTACK_PREVIOUS_LETTER, PAWN_ATTACK_NEXT_LETTER
}
